### ISSUE TITLE
Traduzione nomi

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#12]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L18
in questo while ci sono usati solo variabili con nomi italiani, correggere con verione in inglese

**Comment by Wabri** [comment]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L20 questo mix italiano inglese è molto simpatico

**Comment by DanerSound** [comment]
grazie, il codice deve anche divertire : D

**Comment by DanerSound** [comment]
fixato
