### ISSUE TITLE
GenerarteOstacoliValues

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#14]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L25
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L26
C'è veramente bisogno di avere 2 contatori sul numero di misure e sull'indice dell'array?

**Comment by Wabri** [comment]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L21
Non so se te ne sei accorto, ma questa linea di codice la puoi integrare con la linea:
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L23
Attualmente sovrascrivi la variabile misura per poi sovrascriverla di nuovo.

**Comment by Wabri** [comment]
Poi ci sarebbe da rifattorizzare il codice per evitare la creazione di oggetti inutili, tipo:
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L11
che usi qui:
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L20
quando potresti direttamente scrivere:
`char ostacoloType = alphabet.charAt((new Random()).nextInt(alphabet.length()));`
Evitando in questo modo di creare l'oggetto Random r e alleggerire il codice.

**Comment by Wabri** [comment]
Infine la variabile ostacoloType e distance potrebbero essere evitate semplicemente mettendo la loro implementazione dirattamente nell'assegnazione di vett[arrayIndex], di conseguenza anche la variabile misura sarà completamente inutile. Con queste modifiche il codice dovrebbe diventare più leggero e leggibile.

**Comment by DanerSound** [comment]
per quanto riguarda il primo punto, usare due contantori è stato il modo più semplice per scorrere array e controllare la guardia....(è tardi...) di sicuro ce un modo inteligente per controllare contemporaneamente le due cose ma ci penso più tardi

**Comment by Wabri** [comment]
I due indici hanno lo stesso valore per ogni iterazione del ciclo

**Comment by DanerSound** [comment]
fixato
