### ISSUE TITLE
writeValues della classe ValueOstacoli

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#15]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L38
Perchè parti da i=1 e non da 0? perdi il primo, errore di battitura o ha un significato?

**Comment by Wabri** [comment]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L40
Qui potresti passare direttamente l'assegnazione che hai dato alla variabile content, evitando di creare un oggetto inutile (content per l'appunto).

**Comment by Wabri** [comment]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueOstacoli.java#L41
Se volevi fare una sorta di DEBUG magari articolalo un po' di più, magari mettendo anche il valore assegnato con quell'indice specifico.

**Comment by DanerSound** [comment]
il primo punto l'ho gia fixato in un'altro isuee #22

**Comment by DanerSound** [comment]
ho corretto il secondo punto e il terzo punto si , volevo vedere i valori che stampava... mi deve essere sfugito quando cancellavo la roba
