### ISSUE TITLE
randInt nella classe ValuePendenza

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#16]
Ci sarebbe da fattorizzare molto: if senza parentesi, tabulazione non giusta e spazi vari. Inoltre è probabile che la variabile rand si possa integrare con l'assegnazione dell'array vett, ma non so quale sia il costo computazionale della creazione di un oggetto di tipo Random. Il codice effettivo è:
```
public Random() {
        this(seedUniquifier() ^ System.nanoTime());
    }

    private static long seedUniquifier() {
        // L'Ecuyer, "Tables of Linear Congruential Generators of
        // Different Sizes and Good Lattice Structure", 1999
        for (;;) {
            long current = seedUniquifier.get();
            long next = current * 181783497276652981L;
            if (seedUniquifier.compareAndSet(current, next))
                return next;
        }
    }
```
In cui indirettamente c'è un ciclo infinito che potrebbe rallentare se chiamato più volte, direi quindi che chiamare una sola volta il costruttore è la maniera migliore per evitare sprechi di complessità temporale. In poche parole va bene così.

**Comment by DanerSound** [comment]
diacan

**Comment by Wabri** [comment]
risolto con Merge della PR #21
