### ISSUE TITLE
writeValues nella classe ValuePendenza

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#17]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValuePendenza.java#L24
sei sicuro che questo ciclo debba partire da 1? se si, spiegamelo!

**Comment by Wabri** [comment]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValuePendenza.java#L32
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValuePendenza.java#L34
Due if senza parentesi, non danno problemi ma per convenzione si mettono sempre.

**Comment by DanerSound** [comment]
Le parentesi le ho tolte perche mi davano fastidio avendo una sola riga da eseguire, pero hai ragione devo rispettare la convenzione d'ora in poi le metterò

**Comment by DanerSound** [comment]
per quanto riguarda il primo commento, come avrai intutito ho scritto il metodo in modo tale da cambiare solo il nome del file. quando ho scritto gli altri file ho solo copiato e incolatto.
Quel 1 è un errore ma l'ho lasciato perche la classe ValueSterzo ha un problema di indici : mi stampa due null che non dovrebbe

**Comment by Wabri** [comment]
ci sarebbe da capire perchè
