### ISSUE TITLE
generatedNumbers nella classe ValueSterzo

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#18]
https://github.com/DanerSound/Value-ControlGenerartor/blob/9e72ba157113297992be0643ffdd719a4ab28f1f/ValueGenerator/src/base/ValueSterzo.java#L9
Perchè creare un metodo statico?

**Comment by DanerSound** [comment]
ah... era una cosa che devovo togliere prima di chiamare te ma poi mi sono scordato... nelle prime prove non mi mettevo a crea oggettini , lo corregero nella versione finale quando avro mergiato le varie soluzioni .

**Comment by DanerSound** [comment]
fixatoo nel merg finale
