### ISSUE TITLE
WriteValues nella classe WriteOnFile

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#19]
Non so se te ne sei accorto ma il metodo writeValues è uguale per le 3 classi principali se non per il nome del file su cui scrive. Non potresti prendere il nome da argomento o astrarre un campo? Se astrai il campo basterà portare nella superclasse WriteOnFile il metodo WriteValues che richiamerà il campo relativo alla classe chiamante.

**Comment by DanerSound** [comment]
allora  la classe WriteOnFile deve essere una interfaccia e non una classe Astratta?

**Comment by DanerSound** [comment]
non so come fareeeeeee! xD

**Comment by Wabri** [comment]
vedi #20
