### ISSUE TITLE
Modifica allo schema delle classi

### ISSUE THREAD

**Issue by Wabri** [DanerSound/Value-ControlGenerartor#20]
Avrai notato che i metodi generatedNumbers e randInt relativamente delle classi ValueSterzo e ValuePendenza fanno la stessa cosa a meno di un range di definizione per quanto riguarda ValuePendenza. Puoi quindi fattorizzare queste 2 classi in una classe sola dando una generalizzazione ancora migliore. La cosa migliore da fare sarebbe: 
![class diagram](https://user-images.githubusercontent.com/12409541/38098147-8c3cf8a4-3377-11e8-959d-12fb7d3f6bcd.jpeg)
che dovrebbe essere una cosa del genere:
```
public abstract class RandomStringArrayGenerator {

	public String generate(int arrayLenght) {
		String arrayGen = "";
		for (int i = 0; i < arrayLenght; i++) {
			arrayGen += getNewRandomObject();
		}
		return arrayGen;
	}

	protected abstract String getNewRandomObject();

}

import java.util.Random;

public class StringArrayOfIntegerInRangeGenerator extends RandomStringArrayGenerator {

	private int maxValue;
	private int minValue;

	public StringArrayOfIntegerInRangeGenerator(int maxValue, int minValue) {
		this.maxValue = maxValue;
		this.minValue = minValue;
	}

	@Override
	protected String getNewRandomObject() {
		return String.valueOf((new Random()).nextInt((maxValue - minValue) + 1) + minValue) + " ";
	}

	public int getMaxValue() {
		return maxValue;
	}

	public int getMinValue() {
		return minValue;
	}
}

import java.util.Random;

public class StringArrayOfAlphanumericInRangeGenerator extends StringArrayOfIntegerInRangeGenerator {

	private String alphabet;

	public StringArrayOfAlphanumericInRangeGenerator(String alphabet, int minValue, int maxValue) {
		super(maxValue, minValue);
		this.alphabet = alphabet;
	}

	@Override
	protected String getNewRandomObject() {
		return String.valueOf(getAlphabet().charAt((new Random()).nextInt(getAlphabet().length())))
				+ String.valueOf((new Random()).nextInt((getMaxValue() - getMinValue()) + 1) + getMinValue()) + " ";
	}

	public String getAlphabet() {
		return alphabet;
	}
}
```
A questo punto dovresti creare una classe che scrive su file che assume in ingresso il percorso o il nome del file e la stringa creata con le classi sopra, tipo questa:
```
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class WriteOnFile {
	public static void writeValues(String nameOfFile, String stringToWrite) {
		BufferedWriter bw = null;
		FileWriter fw = null;
		try {
			fw = new FileWriter(nameOfFile);
			bw = new BufferedWriter(fw);
			for (int i = 0; i < stringToWrite.length(); i++) {
				bw.write(stringToWrite.substring(i, i + 1));
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (bw != null)
					bw.close();
				if (fw != null)
					fw.close();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}
	}
}
```
Il Main per generare i nostri file, per esempio 100 elementi scritti sul file chiamato pendenzaValues.txt, sarà del tipo:
```
public class Main {

	public static void main(String[] args) {
		WriteOnFile.writeValues("pendenzaValues.txt", new StringArrayOfAlphanumericInRangeGenerator("AB", 0, 100).generate(100));
	}

}
```
Che genererà un file di questo tipo:
`A67 B62 B43 A4 A23 B15 A3 B62 B97 B21 A31 B53 A65 B0 A82 B5 B52 A12 A93 A61 B42 B40 A29 A80 A38 A88 A97 A14 A49 B69 B7 A69 A48 A42 A95 A48 B78 A1 A52 A62 B99 B20 B23 B18 B85 A98 B69 B63 B8 B30 B56 A96 A16 B55 A87 B74 B39 A29 A31 B42 A65 A22 A5 A52 B15 B1 B100 A52 A18 B92 A75 A98 B10 A0 A46 B95 A62 A49 A83 B6 B41 B91 B90 A48 B36 B88 A16 B52 A21 B29 A6 B21 B74 B7 A87 A79 A36 A85 A16 B36`
Spero di essere stato utile :+1:

**Comment by Wabri** [comment]
Potresti anche fare una richiesta da terminale per richiedere il tipo di stringa da generare e il nome del file dove inserire questi valori. non sarebbe male.

**Comment by Wabri** [comment]
Dovrebbe venire una roba del genere:
![](https://user-images.githubusercontent.com/12409541/38099442-e5ac588c-337a-11e8-9cea-136dbf286190.png)

**Comment by DanerSound** [comment]
Ho letto infatti hai ragione, metterò questa modifica nel release 0.2 ... really thanks man :-*

**Comment by DanerSound** [comment]
ah ! l'ultima parte ti giuro l'ho fatta senza avere letto il tuo sugerimento, perche ho pensato al modo più semplice per passare i nomi ai metodi! e cavolo quello era il più ovvio! e il più semplice visto quello che dovevo fare!
